name: Typescript eslint
on:
  pull_request:
    branches:
      - trunk
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    name: E2E Tests lint with eslint
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Run Typescript eslint
        run: npm run lint